In [ ]:
%matplotlib inline

import pandas as pd
import numpy as np
import matplotlib
from matplotlib import pyplot as plt

from sklearn import preprocessing
from sklearn.model_selection import train_test_split 
from sklearn.linear_model import LinearRegression, Ridge, Lasso

import numpy.polynomial.polynomial as poly

In [ ]:
def get_clean_data(file):
    # Reads panadas dataframe
    df = pd.read_csv(file)
    # Convert datetime to a number
    df['SALE DATE'] = pd.to_datetime(df['SALE DATE']).astype(np.int64)
    # Drop other unneeded columns
    data = df.drop(columns = ["NEIGHBORHOOD", "APARTMENT NUMBER", "BUILDING CLASS CATEGORY", "TAX CLASS AT PRESENT", "BUILDING CLASS AT PRESENT", "BOROUGH", "EASE-MENT", "ADDRESS", "ZIP CODE", "BUILDING CLASS AT TIME OF SALE", "TOTAL UNITS"])
    # Convert all other strings to int values
    data = data.astype(int)
    # print(x.info())
    return data

In [ ]:
def no_feature_scaling(df):
    df_x = df[["BLOCK","LOT","RESIDENTIAL UNITS","COMMERCIAL UNITS","LAND SQUARE FEET", "GROSS SQUARE FEET","YEAR BUILT","TAX CLASS AT TIME OF SALE","SALE DATE"]]
    df_y = df[["SALE PRICE"]]

    x_array = np.array(df_x)
    y_array = np.array(df_y)
    
    X_train, X_test, y_train, y_test = train_test_split(x_array, y_array, test_size = 0.15, train_size = 0.85)
    return X_train, y_train

In [ ]:
def preprocess_scale_data(df):
    df_x_prescale = df[["BLOCK","LOT","RESIDENTIAL UNITS","COMMERCIAL UNITS","LAND SQUARE FEET", "GROSS SQUARE FEET","YEAR BUILT","TAX CLASS AT TIME OF SALE","SALE DATE"]]
    df_y = df[["SALE PRICE"]]

    x_scaled_array = preprocessing.scale(df_x_prescale)
    y_scaled_array = preprocessing.scale(df_y)
    # y_array = np.array(df_y)
    
    # test_size = 0.8, train_size = 0.2
    # test_size = 0.15, train_size = 0.85
    X_train, X_test, y_train, y_test = train_test_split(x_scaled_array, y_scaled_array, test_size = 0.8, train_size = 0.2)
    return X_train, y_train

In [ ]:
def preprocess_normalize_data(df):
    df_x_prescale = df[["BLOCK","LOT","RESIDENTIAL UNITS","COMMERCIAL UNITS","LAND SQUARE FEET", "GROSS SQUARE FEET","YEAR BUILT","TAX CLASS AT TIME OF SALE","SALE DATE"]]
    df_y = df[["SALE PRICE"]]
    # print(df_x_prescale)

    x_scaled_array = preprocessing.scale(df_x_prescale)
    y_array = np.array(df_y)

    df_z_scaled = df_x_prescale.copy()
    # print(df_z_scaled)
    # apply normalization technique to Sale Date
    column = 'SALE DATE'
    df_z_scaled[column] = (df_z_scaled[column] - df_z_scaled[column].mean()) / df_z_scaled[column].std()
    # print(df_z_scaled)
    
    X_train, X_test, y_train, y_test = train_test_split(x_scaled_array, y_array, test_size = 0.8, train_size = 0.2)
    return X_train, y_train


In [ ]:
def preprocess_standard_scalar(df):
    df_x_prescale = df[["BLOCK","LOT","RESIDENTIAL UNITS","COMMERCIAL UNITS","LAND SQUARE FEET", "GROSS SQUARE FEET","YEAR BUILT","TAX CLASS AT TIME OF SALE","SALE DATE"]]
    df_y = df[["SALE PRICE"]]

    x_array = np.array(df_x_prescale)
    y_array = np.array(df_y)
    
    X_train, X_test, y_train, y_test = train_test_split(x_array, y_array, test_size = 0.15, train_size = 0.85)

    scaler = preprocessing.StandardScaler().fit(X_train)
    X_scaled = scaler.transform(X_train)

    # scaler2 = preprocessing.StandardScaler().fit(y_train)
    # y_scaled = scaler2.transform(y_train)

    return X_scaled, y_train


In [ ]:
def pre_scale_normalization():
    # df = pd.read_csv("greater_than_1k.csv")
    # df = df.drop(["Column1"], axis=1)
    # print(df)
    # df.shape
    # X = np.array(df)
    # print(X)

    # # Get indexes where name column has value john and 
    # # value column equals to 0.0
    # indexNames = df[(df['SALE PRICE'] == ' -  ') & (df['value'] == 0.0)].index
    # # Delete these row indexes from dataFramedf.drop(indexNames , inplace=True)

    # df_dropped = df.drop(df.index[df['myvar'] == 'specific_name'], inplace = True)
    # print(df_dropped)




    df = pd.read_csv("greater_than_1k.csv")
    df = df.drop(["Column1"], axis=1)

    #print((df['SALE PRICE'] == ' -  '))
    # print(df['YEAR BUILT'] == 0.0)
    null_indicies = df[(df['SALE PRICE'] == ' -  ') | (df['YEAR BUILT'] == 0.0) | (df['LAND SQUARE FEET'] == ' -  ') | (df['GROSS SQUARE FEET'] == ' -  ')].index
    #print(len(indexNames))

    df_dropped = df.drop(index = null_indicies)
    #print(df_dropped)

    #print(df_dropped['SALE PRICE'].astype(int) < 1000)

    # inconsistent_sale_price_indicies = df_dropped[(df_dropped['SALE PRICE'].astype(int) < 1000)].index
    #df_without_inconsistent = df.drop(index = inconsistent_sale_price_indicies)
    #print(inconsistent_sale_price_indicies)
    # print(df_dropped['SALE PRICE'].atype(int) < 1000)
    # df_inconsistent_sale_price
    # print(df[inconsistent_sale_price_indicies])

    # df_without_inconsistent

    # df_dropped.info()
    # df_dropped

    df_dropped['SALE DATE'] = pd.to_datetime(df['SALE DATE']).astype(np.int64)
    # df_dropped["SALE DATE"]
    x = df_dropped.drop(columns = ["NEIGHBORHOOD", "APARTMENT NUMBER", "BUILDING CLASS CATEGORY", "TAX CLASS AT PRESENT", "BUILDING CLASS AT PRESENT", "BOROUGH", "EASE-MENT", "ADDRESS", "ZIP CODE", "BUILDING CLASS AT TIME OF SALE", "TOTAL UNITS"])

    # x["LAND SQUARE FEET"] = x["LAND SQUARE FEET"].astype(int)
    # x["GROSS SQUARE FEET"] = x["GROSS SQUARE FEET"].astype(int)
    x = x.astype(int)
    x.info()

    #print(df["APARTMENT NUMBER"].to_string())
    #x1 = pd.to_string(df["APARTMENT NUMBER"])





    x_prescale = x[["BLOCK","LOT","RESIDENTIAL UNITS","COMMERCIAL UNITS","LAND SQUARE FEET", "GROSS SQUARE FEET","YEAR BUILT","TAX CLASS AT TIME OF SALE","SALE DATE"]]
    y = x[["SALE PRICE"]]
    # print(x_prescale.shape)
    x_scaled = preprocessing.scale(x_prescale)
    #x_scaled
    type(x_scaled)

    # print(len(x_scaled[0]))
    y_array = np.array(y)
    X_train, X_test, y_train, y_test = train_test_split(x_scaled, y_array, test_size = 0.15, train_size = 0.85)

    linear_reg = LinearRegression()
    linear_reg.fit(X_train, y_train)
    yhat = linear_reg.predict(X_train)
    print("Coefficients", linear_reg.coef_)
    print("Intercept", linear_reg.intercept_)
    print("Score", linear_reg.score(X_train, y_train))

    # print(np.mean(yhat))
    print(y_train)
    RSS = np.sum((yhat - y_train)**2)
    TSS = np.sum((y_train - np.mean(y_train))**2)
    Rsquared = 1- RSS/TSS
    print("RSS", RSS, "TSS",TSS)
    print("R^2",Rsquared)




    # copy the data
    df_z_scaled = x_prescale.copy()
    
    # apply normalization technique to Sale Date
    column = 'SALE DATE'
    df_z_scaled[column] = (df_z_scaled[column] - df_z_scaled[column].mean()) / df_z_scaled[column].std()    
    print(df_z_scaled)

    y = x[["SALE PRICE"]]

    y_array = np.array(y)
    X_train, X_test, y_train, y_test = train_test_split(x_scaled, y_array, test_size = 0.8, train_size = 0.2)

    linear_reg = LinearRegression()
    linear_reg.fit(X_train, y_train)
    yhat = linear_reg.predict(X_train)
    print("Coefficients", linear_reg.coef_)
    print("Intercept", linear_reg.intercept_)
    print("R^2 Score", linear_reg.score(X_train, y_train))

    '''
    # print(np.mean(yhat))
    print(y_train)
    RSS = np.sum((yhat - y_train)**2)
    TSS = np.sum((y_train - np.mean(y_train))**2)
    Rsquared = 1- RSS/TSS
    print("RSS", RSS, "TSS",TSS)
    print("R^2",Rsquared)
    '''

pre_scale_normalization()

# Regular Multiple Linear Regression

In [ ]:
def train_linear(X_train, y_train):
    linear_reg = LinearRegression()
    linear_reg.fit(X_train, y_train)

    # yhat = linear_reg.predict(X_train)
    # RSS = np.sum((yhat - y_train)**2)
    # TSS = np.sum((y_train - np.mean(y_train))**2)
    # R2 = 1- RSS/TSS

    return linear_reg.coef_, linear_reg.intercept_, linear_reg.score(X_train, y_train)

In [ ]:
data = get_clean_data("cleaned_data.csv")
# print(data)
# print(data.info)

# X_train, y_train = no_feature_scaling(data)
# X_train, y_train = preprocess_scale_data(data)
X_train, y_train = preprocess_normalize_data(data)
# X_train, y_train = preprocess_standard_scalar(data)

coef, inter, score = train_linear(X_train, y_train)
print("Coefficients", coef)
print("Intercept", inter)
print("Score", score)

Coefficients [[  -174146.51578568    565296.33223087 -18980347.02651202
    6418837.67075773 -11760507.13736631  36680015.93984197
    -299042.89633517  -1474957.68383601    144093.78113136]]
Intercept [1645770.37461079]
Score 0.8803709829580303
/shared-libs/python3.7/py/lib/python3.7/site-packages/sklearn/preprocessing/_data.py:194: UserWarning: Numerical issues were encountered when centering the data and might not be solved. Dataset may contain too large values. You may need to prescale your features.
  warnings.warn("Numerical issues were encountered "


In [ ]:
data = get_clean_data("cleaned_data.csv")
# print(data)
# print(data.info)

for i in range(4):
    if i == 0: X_train, y_train = no_feature_scaling(data)
    elif i == 1: X_train, y_train = preprocess_scale_data(data)
    elif i == 2: X_train, y_train = preprocess_normalize_data(data)
    elif i == 3: X_train, y_train = preprocess_standard_scalar(data)

    coef, inter, score = train_linear(X_train, y_train)
    # print("Coefficients", coef)
    # print("Intercept", inter)
    print("Score", score)

Score 0.5512370155327757
Score 0.31472933411675885
Score 0.805721686151032
Score 0.5473853066584895
/shared-libs/python3.7/py/lib/python3.7/site-packages/sklearn/preprocessing/_data.py:194: UserWarning: Numerical issues were encountered when centering the data and might not be solved. Dataset may contain too large values. You may need to prescale your features.
  warnings.warn("Numerical issues were encountered "
/shared-libs/python3.7/py/lib/python3.7/site-packages/sklearn/preprocessing/_data.py:194: UserWarning: Numerical issues were encountered when centering the data and might not be solved. Dataset may contain too large values. You may need to prescale your features.
  warnings.warn("Numerical issues were encountered "


In [ ]:
data = get_clean_data("cleaned_data.csv")
X_train, y_train = preprocess_normalize_data(data)
coef, inter, score = train_linear(X_train, y_train)
print(score)
print(X_train.dot(coef.T) + inter)
print(y_train)

0.8395058663767565
[[  563260.70816494]
 [ 3555199.87184169]
 [ 1319250.88817919]
 ...
 [  126869.85673512]
 [  749271.76086301]
 [-1141765.4299602 ]]
[[345000]
 [307224]
 [995000]
 ...
 [665000]
 [712775]
 [433890]]
/shared-libs/python3.7/py/lib/python3.7/site-packages/sklearn/preprocessing/_data.py:194: UserWarning: Numerical issues were encountered when centering the data and might not be solved. Dataset may contain too large values. You may need to prescale your features.
  warnings.warn("Numerical issues were encountered "


# Polynomial Feature Transformation

In [ ]:
def polynomial_regression(X_train, y_train, degree):
    poly_features = preprocessing.PolynomialFeatures(degree = degree, include_bias = False)
    print(X_train)
    X_poly = poly_features.fit_transform(X_train)
    return X_poly

In [ ]:
def polynomial_regression2(X_tr, y_tr):
    validation_costs = []
    train_costs = []
    theta_dict = {}
    model_degree = range(1, 11)

    for d in model_degree:
        # print('Order: ', d)
        theta = poly.polyfit(X_tr, y_tr, d)
        yhat = poly.polyval(X_val, theta)
        validation_cost = np.mean((yhat - y_val) ** 2)
        theta_dict[d] = theta
        validation_costs.append(validation_cost)
        # # if d == 1:
        # w0 = theta[0]
        # w1 = theta[1]
        # for j in range(10):
        #   x1 = X_val[j]
        #   yhet1 = w0 + w1 * x1
        #   print("yhet1", yhet1)
        # print('Theta: ', theta)
        # print("Validation Cost: ", validation_costs)
        # print("yhat: ", yhat)
        yhat_train = poly.polyval(X_tr, theta)
        train_cost = np.mean((yhat_train - y_tr) ** 2)
        train_costs.append(train_cost)
        # print('Train cost: ', train_cost)
        # print('-------------------------')

    # print("Train Costs:", train_costs)
    # print("Validation Costs:", validation_costs)
    # min_cost_index = np.argmin(validation_costs)
    # print("Best Model Degree:", min_cost_index + 1)
    # print(theta_dict[min_cost_index + 1])

In [ ]:
data = get_clean_data("cleaned_data.csv")
X_train, y_train = preprocess_normalize_data(data)
X_poly = polynomial_regression(X_train, y_train, 2)
# X_poly = polynomial_regression2(X_train, y_train)
coef, inter, score = train_linear(X_poly, y_train)
# print("Coefficients", coef)
# print("Intercept", inter)
print("Score", score)

[[-0.80552242 -0.44624325 -0.13824403 ...  0.28725656  3.4944635
  -0.04485267]
 [-0.32463718 -0.43155889 -0.13824403 ... -4.46976288  3.4944635
  -0.64886243]
 [ 0.6839281  -0.33086616 -0.08193742 ...  0.17152573 -0.55614862
   0.74131876]
 ...
 [ 0.5039058  -0.34764828 -0.08193742 ...  0.31618927 -0.55614862
   1.30697869]
 [ 0.33406825 -0.2679332  -0.08193742 ...  0.38852104 -0.55614862
  -0.87896138]
 [-0.54897689 -0.38121253  0.19959563 ...  0.18599209  0.79405542
  -0.84061156]]
Score 0.9828645889712995
/shared-libs/python3.7/py/lib/python3.7/site-packages/sklearn/preprocessing/_data.py:194: UserWarning: Numerical issues were encountered when centering the data and might not be solved. Dataset may contain too large values. You may need to prescale your features.
  warnings.warn("Numerical issues were encountered "


In [ ]:
print(X_poly.dot(coef.T) + inter)
print(y_train)

[[10848150.08484664]
 [-2168184.08086241]
 [  393490.96663062]
 ...
 [  131077.66710808]
 [   90243.72649328]
 [ 2620967.46971145]]
[[1400000]
 [ 500000]
 [ 800000]
 ...
 [ 510000]
 [1812485]
 [ 999000]]


# Ridge Regularization

In [ ]:
def ridge_regularization(X_train, y_train, alpha):
    reg = Ridge(alpha=alpha)
    reg.fit(X_train, y_train)
    return reg.coef_, reg.intercept_, reg.score(X_train, y_train)

In [ ]:
data = get_clean_data("cleaned_data.csv")
X_train, y_train = preprocess_normalize_data(data)
coef, inter, score = ridge_regularization(X_train, y_train, 0.5)
# print("Coefficients", coef)
# print("Intercept", inter)
print("Score", score)

Score 0.8305372055063678
/shared-libs/python3.7/py/lib/python3.7/site-packages/sklearn/preprocessing/_data.py:194: UserWarning: Numerical issues were encountered when centering the data and might not be solved. Dataset may contain too large values. You may need to prescale your features.
  warnings.warn("Numerical issues were encountered "


In [ ]:
data = get_clean_data("cleaned_data.csv")
X_train, y_train = preprocess_normalize_data(data)
ridge_alpha_space = np.linspace(0,1,11)
for i in ridge_alpha_space:
    coef, inter, score = ridge_regularization(X_train, y_train, i)
    # print("Coefficients", coef)
    # print("Intercept", inter)
    print("Alpha", i, "Score", score)

Alpha 0.0 Score 0.833618302972984
Alpha 0.1 Score 0.8336183024573919
Alpha 0.2 Score 0.8336183009108071
Alpha 0.30000000000000004 Score 0.8336182983335161
Alpha 0.4 Score 0.8336182947258055
Alpha 0.5 Score 0.8336182900879621
Alpha 0.6000000000000001 Score 0.8336182844202719
Alpha 0.7000000000000001 Score 0.8336182777230211
Alpha 0.8 Score 0.8336182699964959
Alpha 0.9 Score 0.8336182612409824
Alpha 1.0 Score 0.8336182514567663
/shared-libs/python3.7/py/lib/python3.7/site-packages/sklearn/preprocessing/_data.py:194: UserWarning: Numerical issues were encountered when centering the data and might not be solved. Dataset may contain too large values. You may need to prescale your features.
  warnings.warn("Numerical issues were encountered "


# Lasso Regularization

In [ ]:
def lasso_regularization(X_train, y_train, alpha):
    reg = Lasso(alpha=alpha)
    reg.fit(X_train, y_train)
    return reg.coef_, reg.intercept_, reg.score(X_train, y_train)

In [ ]:
data = get_clean_data("cleaned_data.csv")
X_train, y_train = preprocess_normalize_data(data)
coef, inter, score = lasso_regularization(X_train, y_train, 0.5)
# print("Coefficients", coef)
# print("Intercept", inter)
print("Score", score)

Score 0.8596074145847836
/shared-libs/python3.7/py/lib/python3.7/site-packages/sklearn/preprocessing/_data.py:194: UserWarning: Numerical issues were encountered when centering the data and might not be solved. Dataset may contain too large values. You may need to prescale your features.
  warnings.warn("Numerical issues were encountered "


In [ ]:
data = get_clean_data("cleaned_data.csv")
X_train, y_train = preprocess_normalize_data(data)
ridge_alpha_space = np.linspace(0,1,11)
for i in ridge_alpha_space:
    coef, inter, score = lasso_regularization(X_train, y_train, i)
    # print("Coefficients", coef)
    # print("Intercept", inter)
    print("Alpha", i, "Score", score)

/shared-libs/python3.7/py/lib/python3.7/site-packages/sklearn/preprocessing/_data.py:194: UserWarning: Numerical issues were encountered when centering the data and might not be solved. Dataset may contain too large values. You may need to prescale your features.
  warnings.warn("Numerical issues were encountered "
/shared-libs/python3.7/py-core/lib/python3.7/site-packages/ipykernel_launcher.py:3: UserWarning: With alpha=0, this algorithm does not converge well. You are advised to use the LinearRegression estimator
  This is separate from the ipykernel package so we can avoid doing imports until
/shared-libs/python3.7/py/lib/python3.7/site-packages/sklearn/linear_model/_coordinate_descent.py:532: UserWarning: Coordinate descent with no regularization may lead to unexpected results and is discouraged.
  positive)
/shared-libs/python3.7/py/lib/python3.7/site-packages/sklearn/linear_model/_coordinate_descent.py:532: ConvergenceWarning: Objective did not converge. You might want to increas

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=90fab6ac-739b-4c97-b68c-ff3c09208031' target="_blank">
 </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>